name: Node.js Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18 # sync with ./publish.yml
        cache: 'npm'
    - run: npm install --save-dev hardhat
    - run: npx hardhat test
